name: 'ABC Tunes Compiler'
description: 'Compiles ABC notation files into high-quality PDFs and MP3s.'
author: 'Matt'
inputs:
  abc_dir:
    description: 'The folder containing your .abc files'
    required: false
    default: 'abcs'
  file_name:
    description: 'The specific ABC file to process (without extension)'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_ABC_DIR: ${{ inputs.abc_dir }}
    INPUT_FILE_NAME: ${{ inputs.file_name }}
    INPUT_PDF_DIR: 'pdfs'
    INPUT_MP3_DIR: 'mp3s'
    INPUT_CSV_DIR: 'csvs'
  args:
    - /scripts/action_entrypoint.sh
