name: Test Action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Action
        uses: ./
        with:
          abc_dir: 'tests'
          pdf_dir: 'out_pdfs'
          mp3_dir: 'out_mp3s'
          csv_dir: 'out_csvs'
      - name: Verify Output
        run: |
          ls -R
          test -f out_pdfs/test.pdf
          test -f out_mp3s/test.mp3
          test -f out_csvs/test.csv
